INSERT INTO vat_decisions (
  vat_decision_id,
  company_id,
  source_type,
  source_id,
  decision_code,
  rule_pack_id,
  explanation_json,
  vat_code,
  rule_pack_version,
  source_snapshot_date,
  inputs_hash,
  effective_date,
  status,
  declaration_box_codes_json,
  booking_template_code,
  outputs_json,
  warnings_json,
  review_queue_code,
  review_queue_item_id,
  created_by_actor_id,
  decision_category,
  invoice_text_requirements_json,
  credit_note_flag,
  original_vat_decision_id,
  transaction_line_json,
  reporting_channel,
  eu_list_eligible,
  oss_record_json,
  ioss_record_json
)
VALUES
  (
    '00000000-0000-4000-8000-000000001011',
    '00000000-0000-4000-8000-000000000001',
    'AR_INVOICE',
    'phase4-vat-reporting-demo-domestic',
    'VAT_SE_DOMESTIC_25',
    'vat-se-2026.3',
    '[
      "rule_pack_id=vat-se-2026.3",
      "vat_code=VAT_SE_DOMESTIC_25",
      "scenario=domestic_standard_sale"
    ]'::jsonb,
    'VAT_SE_DOMESTIC_25',
    '2026.3',
    DATE '2026-03-21',
    'phase4-vat-reporting-demo-domestic-hash',
    DATE '2026-03-21',
    'decided',
    '["05","10"]'::jsonb,
    'vat_se_domestic_25',
    '{"decisionCategory":"domestic_standard_sale","declarationBoxCodes":["05","10"],"declarationBoxAmounts":[{"boxCode":"05","amount":1000,"amountType":"taxable_base"},{"boxCode":"10","amount":250,"amountType":"output_vat"}],"postingEntries":[{"entryCode":"net_sale","direction":"credit","amount":1000,"vatEffect":"taxable_base"},{"entryCode":"output_vat","direction":"credit","amount":250,"vatEffect":"output_vat"}],"reportingChannel":"regular_vat_return","euListEligible":false,"ossRecord":null,"iossRecord":null}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    'system',
    'domestic_standard_sale',
    '[]'::jsonb,
    FALSE,
    NULL,
    '{"seller_country":"SE","seller_vat_registration_country":"SE","buyer_country":"SE","buyer_type":"business","buyer_vat_no":"SE556677889901","supply_type":"sale","goods_or_services":"goods","invoice_date":"2026-03-21","delivery_date":"2026-03-21","currency":"SEK","line_amount_ex_vat":1000,"vat_rate":25,"vat_code_candidate":"VAT_SE_DOMESTIC_25","project_id":"00000000-0000-4000-8000-000000000041","source_type":"AR_INVOICE","source_id":"phase4-vat-reporting-demo-domestic","buyer_is_taxable_person":true,"buyer_vat_number":"SE556677889901","buyer_vat_number_status":"valid","supply_subtype":"standard","property_related_flag":false,"construction_service_flag":false,"transport_end_country":"SE","import_flag":false,"export_flag":false,"reverse_charge_flag":false,"oss_flag":false,"ioss_flag":false,"tax_date":"2026-03-21","prepayment_date":"2026-03-21","line_discount":0,"line_quantity":1,"line_uom":"ea","tax_rate_candidate":25,"exemption_reason":"not_applicable","invoice_text_code":"domestic_standard","report_box_code":"05","credit_note_flag":false,"original_vat_decision_id":null,"deduction_ratio":null,"ecb_exchange_rate_to_eur":null,"consignment_value_eur":null,"region":"SE"}'::jsonb,
    'regular_vat_return',
    FALSE,
    NULL,
    NULL
  ),
  (
    '00000000-0000-4000-8000-000000001012',
    '00000000-0000-4000-8000-000000000001',
    'AR_INVOICE',
    'phase4-vat-reporting-demo-oss',
    'VAT_SE_EU_B2C_OSS',
    'vat-se-2026.3',
    '[
      "rule_pack_id=vat-se-2026.3",
      "vat_code=VAT_SE_EU_B2C_OSS",
      "scenario=eu_b2c_oss_sale"
    ]'::jsonb,
    'VAT_SE_EU_B2C_OSS',
    '2026.3',
    DATE '2026-03-21',
    'phase4-vat-reporting-demo-oss-hash',
    DATE '2026-03-21',
    'decided',
    '["OSS"]'::jsonb,
    'vat_se_eu_b2c_oss',
    '{"decisionCategory":"eu_b2c_oss_sale","declarationBoxCodes":["OSS"],"declarationBoxAmounts":[{"boxCode":"OSS","amount":200,"amountType":"taxable_base"}],"postingEntries":[{"entryCode":"net_sale","direction":"credit","amount":200,"vatEffect":"taxable_base"},{"entryCode":"output_vat","direction":"credit","amount":50,"vatEffect":"output_vat"}],"reportingChannel":"oss","euListEligible":false,"ossRecord":{"scheme":"oss","identifierState":"SE","orderType":"union","buyerCountry":"FR","vatRate":25,"euroBaseAmount":200,"euroVatAmount":50,"originalCurrency":"EUR","exchangeRateToEur":1,"consignmentValueEur":null},"iossRecord":null}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    'system',
    'eu_b2c_oss_sale',
    '[]'::jsonb,
    FALSE,
    NULL,
    '{"seller_country":"SE","seller_vat_registration_country":"SE","buyer_country":"FR","buyer_type":"consumer","buyer_vat_no":"NOT-REGISTERED","supply_type":"sale","goods_or_services":"goods","invoice_date":"2026-03-21","delivery_date":"2026-03-21","currency":"EUR","line_amount_ex_vat":200,"vat_rate":25,"vat_code_candidate":"VAT_SE_EU_B2C_OSS","project_id":"00000000-0000-4000-8000-000000000041","source_type":"AR_INVOICE","source_id":"phase4-vat-reporting-demo-oss","buyer_is_taxable_person":false,"buyer_vat_number":"NOT-REGISTERED","buyer_vat_number_status":"not_applicable","supply_subtype":"standard","property_related_flag":false,"construction_service_flag":false,"transport_end_country":"FR","import_flag":false,"export_flag":false,"reverse_charge_flag":false,"oss_flag":true,"ioss_flag":false,"tax_date":"2026-03-21","prepayment_date":"2026-03-21","line_discount":0,"line_quantity":1,"line_uom":"ea","tax_rate_candidate":25,"exemption_reason":"not_applicable","invoice_text_code":"oss_sale","report_box_code":"OSS","credit_note_flag":false,"original_vat_decision_id":null,"deduction_ratio":null,"ecb_exchange_rate_to_eur":1,"consignment_value_eur":null,"region":"EU"}'::jsonb,
    'oss',
    FALSE,
    '{"scheme":"oss","identifierState":"SE","orderType":"union","buyerCountry":"FR","vatRate":25,"euroBaseAmount":200,"euroVatAmount":50,"originalCurrency":"EUR","exchangeRateToEur":1,"consignmentValueEur":null}'::jsonb,
    NULL
  ),
  (
    '00000000-0000-4000-8000-000000001013',
    '00000000-0000-4000-8000-000000000001',
    'AR_INVOICE',
    'phase4-vat-reporting-demo-eu-goods',
    'VAT_SE_EU_GOODS_B2B',
    'vat-se-2026.3',
    '[
      "rule_pack_id=vat-se-2026.3",
      "vat_code=VAT_SE_EU_GOODS_B2B",
      "scenario=eu_goods_b2b_sale"
    ]'::jsonb,
    'VAT_SE_EU_GOODS_B2B',
    '2026.3',
    DATE '2026-03-21',
    'phase4-vat-reporting-demo-eu-goods-hash',
    DATE '2026-03-21',
    'decided',
    '["35"]'::jsonb,
    'vat_se_eu_goods_b2b',
    '{"decisionCategory":"eu_goods_b2b_sale","declarationBoxCodes":["35"],"declarationBoxAmounts":[{"boxCode":"35","amount":900,"amountType":"taxable_base"}],"postingEntries":[{"entryCode":"net_sale","direction":"credit","amount":900,"vatEffect":"taxable_base"}],"reportingChannel":"regular_vat_return","euListEligible":true,"ossRecord":null,"iossRecord":null}'::jsonb,
    '[]'::jsonb,
    NULL,
    NULL,
    'system',
    'eu_goods_b2b_sale',
    '["buyer_vat_number_required"]'::jsonb,
    FALSE,
    NULL,
    '{"seller_country":"SE","seller_vat_registration_country":"SE","buyer_country":"DK","buyer_type":"business","buyer_vat_no":"DK12345678","supply_type":"sale","goods_or_services":"goods","invoice_date":"2026-03-21","delivery_date":"2026-03-21","currency":"SEK","line_amount_ex_vat":900,"vat_rate":0,"vat_code_candidate":"VAT_SE_EU_GOODS_B2B","project_id":"00000000-0000-4000-8000-000000000041","source_type":"AR_INVOICE","source_id":"phase4-vat-reporting-demo-eu-goods","buyer_is_taxable_person":true,"buyer_vat_number":"DK12345678","buyer_vat_number_status":"valid","supply_subtype":"standard","property_related_flag":false,"construction_service_flag":false,"transport_end_country":"DK","import_flag":false,"export_flag":false,"reverse_charge_flag":false,"oss_flag":false,"ioss_flag":false,"tax_date":"2026-03-21","prepayment_date":"2026-03-21","line_discount":0,"line_quantity":1,"line_uom":"ea","tax_rate_candidate":0,"exemption_reason":"not_applicable","invoice_text_code":"eu_goods_b2b","report_box_code":"35","credit_note_flag":false,"original_vat_decision_id":null,"deduction_ratio":null,"ecb_exchange_rate_to_eur":null,"consignment_value_eur":null,"region":"EU"}'::jsonb,
    'regular_vat_return',
    TRUE,
    NULL,
    NULL
  )
ON CONFLICT (vat_decision_id) DO NOTHING;

INSERT INTO vat_declaration_runs (
  vat_declaration_run_id,
  company_id,
  from_date,
  to_date,
  declaration_box_summary_json,
  oss_summary_json,
  ioss_summary_json,
  ledger_comparison_json,
  previous_submission_id,
  correction_reason,
  changed_boxes_json,
  changed_amounts_json,
  signer,
  submitted_at,
  source_snapshot_hash
)
VALUES (
  '00000000-0000-4000-8000-000000001021',
  '00000000-0000-4000-8000-000000000001',
  DATE '2026-03-01',
  DATE '2026-03-31',
  '[{"boxCode":"05","amountType":"taxable_base","amount":1000},{"boxCode":"10","amountType":"output_vat","amount":250},{"boxCode":"35","amountType":"taxable_base","amount":900}]'::jsonb,
  '[{"scheme":"oss","identifierState":"SE","orderType":"union","buyerCountry":"FR","vatRate":25,"euroBaseAmount":200,"euroVatAmount":50,"originalCurrencies":["EUR"],"exchangeRatesToEur":[1]}]'::jsonb,
  '[]'::jsonb,
  '{"matched":true,"reason":null,"expectedDebit":0,"expectedCredit":2150,"actualDebit":0,"actualCredit":2150,"matchedEntryCount":2,"unmatchedExpectedLineCount":0}'::jsonb,
  NULL,
  NULL,
  '[]'::jsonb,
  '[]'::jsonb,
  'system',
  TIMESTAMPTZ '2026-03-21T12:00:00Z',
  'phase4-vat-reporting-demo-declaration-run-hash'
)
ON CONFLICT (vat_declaration_run_id) DO NOTHING;

INSERT INTO vat_periodic_statement_runs (
  vat_periodic_statement_run_id,
  company_id,
  from_date,
  to_date,
  line_count,
  lines_json,
  previous_submission_id,
  correction_reason,
  source_snapshot_hash,
  generated_at,
  generated_by_actor_id
)
VALUES (
  '00000000-0000-4000-8000-000000001022',
  '00000000-0000-4000-8000-000000000001',
  DATE '2026-03-01',
  DATE '2026-03-31',
  1,
  '[{"customerCountry":"DK","customerVatNumber":"DK12345678","buyerVatNumberStatus":"valid","goodsOrServices":"goods","taxableAmount":900,"decisionIds":["00000000-0000-4000-8000-000000001013"]}]'::jsonb,
  NULL,
  NULL,
  'phase4-vat-reporting-demo-periodic-run-hash',
  TIMESTAMPTZ '2026-03-21T12:05:00Z',
  'system'
)
ON CONFLICT (vat_periodic_statement_run_id) DO NOTHING;
